Lint all Jenkinsfiles in parameters

diff --git a/jenkinslint b/jenkinslint
--- a/jenkinslint
+++ b/jenkinslint
@@ -13,6 +13,9 @@
 # For configuration, use the INIFILE
 INIFILE=.jenkinslintrc
 
+# Init ERROR variable
+ERROR=false
+
 # The following parameters are supported:
 # JENKINS_SERVER= # Server name
 # JENKINS_SSH_PORT=8022 # When set, use SSH validation
@@ -34,14 +37,6 @@ fi
 # Read INI file if it exists
 # shellcheck disable=SC1090
 [[ -f "${INIFILE}" ]] && source <(grep "=" "${INIFILE}")
-
-JENKINS_FILE=${1:-Jenkinsfile}
-if [ ! -f "${JENKINS_FILE}" ]; then
-    echo "Could not find file ${JENKINS_FILE}"
-    exit 1
-else
-    echo "Validating ${JENKINS_FILE}"
-fi
 
 # Disable certificate validation when JENKINS_UNSAFE_SSL parameter is defined
 [[ -n "${JENKINS_UNSAFE_SSL}" ]] && JENKINS_UNSAFE_SSL="-k"
@@ -92,16 +87,42 @@ web_validation(){
 validate(){
     if [[ $result =~ Errors ]]; then
         echo "$result"
-        exit 1
+        ERROR=true
     else
         echo "$result"
+    fi
+}
+
+finish(){
+    if [[ $ERROR ]]; then
+        exit 1
+    else
         exit 0
     fi
 }
 
 if [[ "$JENKINS_SSH_PORT" ]]; then
-    ssh_validation
+    for jenkinsfile in "${@}"
+    do
+        JENKINS_FILE=$jenkinsfile
+        if [ ! -f "${JENKINS_FILE}" ]; then
+            echo "Could not find file ${JENKINS_FILE}"
+        else
+            echo "Validating ${JENKINS_FILE}"
+            ssh_validation
+            validate
+        fi
+    done
 else
-    web_validation
+    for jenkinsfile in "${@}"
+    do
+        JENKINS_FILE=$jenkinsfile
+        if [ ! -f "${JENKINS_FILE}" ]; then
+            echo "Could not find file ${JENKINS_FILE}"
+        else
+            echo "Validating ${JENKINS_FILE}"
+            web_validation
+            validate
+        fi
+    done
 fi
-validate
